### ISSUE TITLE
Tag each release when the PR is merged

### ISSUE THREAD

**Issue by laingsimon** [laingsimon/courage_scores#1152]
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-your-pull_request_target-workflow-when-a-pull-request-merges

```
on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${github.event.pullrequest.title}"
        echo "${github.event.pullrequest.merge_commit_sha}"
        // Add a tag
       - name: checkout
         uses: actions/checkout@v4
      - name: add tag
         run: |
              git tag "${github.event.pullrequest.title}"
              git push
```
