### ISSUE TITLE
Add test reporter to workflows

### ISSUE THREAD

**Issue by laingsimon** [laingsimon/courage_scores#700]
- [x] dotnet
   - `...courage_scores/CourageScores.Tests/TestResults/TestResults.trx`
- [x] react
- [ ] report into workflow run
   - https://github.com/marketplace/actions/test-reporter

**Comment by laingsimon** [comment]
```
name: 'Test Report'
on:
  workflow_run:
    workflows: ['???']           # runs after test workflows
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: dotnet-test-results
        name: NUnit Tests
        path: 'TestResults.xml'                     # Path to test results (inside artifact .zip)
        reporter: NUnit?
    - uses: dorny/test-reporter@v1
      with:
        artifact: jest-test-results
        name: JEST Tests
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: jest-junit
```
